spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?serverTimezone=UTC
    username: "Razakor"
    password: "admin"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false